[project]
name = "freight-rate-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed Taharwah", email = "mtahrawe685@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.8,<4",
    "numpy>=1.26,<3",
    "pandas>=2.0,<3",
    "scikit-learn>=1.9.1",
]

[project.scripts]
freight-rate-prediction = "freight_rate_prediction:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
